# Generated by Django 5.1.3 on 2024-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=100)),
                ('rainfall', models.FloatField()),
                ('temperature', models.FloatField()),
                ('crop_name', models.CharField(max_length=100)),
            ],
        ),
    ]
